import type { ActivityItem, Channel, PollResult, StatusResponse } from './types';

export const MOCK_TOKEN = 'dev-mobile-token';

export const now = '2026-05-04T12:00:00.000Z';

export const seedChannels: Channel[] = [
  {
    channel_id: 101,
    youtube_channel_id: 'UCmockReactNative101',
    title: 'React Native Field Notes',
    is_monitored: true,
    last_seen_video_id: 'rn-latest-001',
    baseline_established_at: '2026-05-01T10:00:00.000Z',
    latest_detected_video: {
      video_id: 501,
      youtube_video_id: 'rn-latest-001',
      title: 'Shipping a Small Expo Admin App',
      youtube_url: 'https://www.youtube.com/watch?v=rn-latest-001',
      published_at: '2026-05-03T16:30:00.000Z',
    },
  },
  {
    channel_id: 102,
    youtube_channel_id: 'UCmockOps102',
    title: 'Backend Ops Weekly',
    is_monitored: true,
    last_seen_video_id: null,
    baseline_established_at: null,
    latest_detected_video: null,
  },
  {
    channel_id: 201,
    youtube_channel_id: 'UCmockMusic201',
    title: 'Catalog Only Music',
    is_monitored: false,
    last_seen_video_id: null,
    baseline_established_at: null,
    latest_detected_video: null,
  },
  {
    channel_id: 202,
    youtube_channel_id: 'UCmockDesign202',
    title: 'Design Systems Archive',
    is_monitored: false,
    last_seen_video_id: 'design-archive-077',
    baseline_established_at: null,
    latest_detected_video: {
      video_id: 502,
      youtube_video_id: 'design-archive-077',
      title: 'Catalog Video Without Monitoring',
      youtube_url: 'https://www.youtube.com/watch?v=design-archive-077',
      published_at: '2026-04-29T09:15:00.000Z',
    },
  },
];

export const basePollResult: PollResult = {
  run_outcome: 'success',
  channels_processed: 2,
  channels_failed: 0,
  baselines_established: 1,
  new_videos_detected: 1,
  quota_blocked: false,
  channel_errors: [],
};

export const seedActivity: ActivityItem[] = [
  {
    activity_id: 9001,
    delivery_id: 8001,
    video_id: 501,
    youtube_video_id: 'rn-latest-001',
    video_title: 'Shipping a Small Expo Admin App',
    youtube_url: 'https://www.youtube.com/watch?v=rn-latest-001',
    channel_id: 101,
    channel_title: 'React Native Field Notes',
    delivery_status: 'delivered',
    published_at: '2026-05-03T16:30:00.000Z',
    detected_at: '2026-05-03T17:00:00.000Z',
    last_attempt_at: '2026-05-03T17:00:05.000Z',
    last_error: null,
  },
  {
    activity_id: 9002,
    delivery_id: 8002,
    video_id: 503,
    youtube_video_id: 'ops-pending-010',
    video_title: 'Monitoring Baselines Explained',
    youtube_url: 'https://www.youtube.com/watch?v=ops-pending-010',
    channel_id: 102,
    channel_title: 'Backend Ops Weekly',
    delivery_status: 'pending',
    published_at: '2026-05-04T08:00:00.000Z',
    detected_at: '2026-05-04T08:30:00.000Z',
    last_attempt_at: null,
    last_error: null,
  },
  {
    activity_id: 9003,
    delivery_id: 8003,
    video_id: 504,
    youtube_video_id: 'ops-retry-011',
    video_title: 'Retryable Delivery Failure Demo',
    youtube_url: 'https://www.youtube.com/watch?v=ops-retry-011',
    channel_id: 102,
    channel_title: 'Backend Ops Weekly',
    delivery_status: 'pending_retry',
    published_at: '2026-05-02T08:00:00.000Z',
    detected_at: '2026-05-02T08:30:00.000Z',
    last_attempt_at: '2026-05-02T08:31:00.000Z',
    last_error: 'Mock transient email provider timeout',
  },
  {
    activity_id: 9004,
    delivery_id: 8004,
    video_id: 505,
    youtube_video_id: 'rn-failed-012',
    video_title: 'Failed Delivery Demo',
    youtube_url: 'https://www.youtube.com/watch?v=rn-failed-012',
    channel_id: 101,
    channel_title: 'React Native Field Notes',
    delivery_status: 'failed',
    published_at: '2026-05-01T11:00:00.000Z',
    detected_at: '2026-05-01T11:30:00.000Z',
    last_attempt_at: '2026-05-01T11:31:00.000Z',
    last_error: 'Mock permanent delivery failure',
  },
];

export const seedStatus: StatusResponse = {
  service: 'ytpipe',
  environment: 'mock',
  ready: true,
  subscription_sync: {
    last_success_at: '2026-05-04T10:00:00.000Z',
    last_error_at: null,
    last_error_message: null,
    metadata: { source: 'mock-mobile-api' },
  },
  polling: {
    last_success_at: now,
    last_error_at: null,
    last_error_message: null,
    last_run: basePollResult,
  },
  email: {
    last_attempt_at: '2026-05-04T08:31:00.000Z',
    last_success_at: '2026-05-03T17:00:05.000Z',
    last_failure_at: '2026-05-02T08:31:00.000Z',
    last_error: null,
    pending_count: 1,
    pending_retry_count: 1,
    delivered_count: 1,
    failed_count: 1,
  },
  quota: {
    daily_quota_budget: 500,
    estimated_units_used_today: 8,
    last_run_estimated_units: 2,
    safety_stop_active: false,
    safety_stop_enabled: true,
    safety_stop_triggered_at: null,
  },
  channels: {
    imported_count: seedChannels.length,
    monitored_count: seedChannels.filter((channel) => channel.is_monitored).length,
  },
};
